AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance with Logstash for log ingestion and processing'

Resources:
  LogstashInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'AMI_ID_PLACEHOLDER'
      SecurityGroupIds:
        - 'SECURITY_GROUP_ID_PLACEHOLDER'
      KeyName: 'KEY_PAIR_NAME_PLACEHOLDER'
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y java-1.8.0
          sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo rpm --import -
          sudo yum install -y logstash
          sudo systemctl start logstash
          sudo systemctl enable logstash
      Tags:
        - Key: 'Name'
          Value: 'LogstashInstance'

Outputs:
  LogstashInstancePublicIp:
    Description: 'Public IP address of the Logstash instance'
    Value: !GetAtt LogstashInstance.PublicIp

